---
name: Shell Check

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: run shellcheck
        uses: azohra/shell-linter@latest
        with:
          path: "litra-glow"
          severity: "warning"
